services:
  - type: web
    name: pizza-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    envVars:
      - key: FLASK_ENV
        value: production